SEOs, Typo Alerts
ncs-jss/ncs-jss.github.io pull request #37
Opened 2020-05-26 13:07 UTC by Shruti3004

2020-05-26 14:56 UTC, rahul2240 commented
Better use commit message as 
"add <something> to <something>", "fix <something> in <something>" etc.

Add commit description 
"it should tell what commit is doing or maybe why you did this"

2nd commit has done nothing, try removing the extra commit else I will help.

2020-05-26 15:02 UTC, Shruti3004 commented
Okay sir
I will do the same.

On Tue, 26 May 2020, 20:26 Rahul, <notifications@github.com> wrote:

> Better use commit message as
> "add to ", "fix in " etc.
>
> Add commit description
> "it should tell what commit is doing or maybe why you did this"
>
> 2nd commit has done nothing, try removing the extra commit else I will
> help.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ncs-jss/ncs-jss.github.io/pull/37#issuecomment-634077971>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMIRF5KX5IGW4WOJWZYEX3RTPKDLANCNFSM4NKJK3QQ>
> .
>

2020-05-26 16:00 UTC, rajat2502 commented
Also, make different PRs for different issues/tasks.

2020-05-26 16:03 UTC, Shruti3004 commented
okay sir

2020-05-26 16:51 UTC, rajat2502 requested changes

2020-05-26 16:51 UTC, rajat2502 commented on index.html
> +    <meta name="description" content="Nibble Computer Society">
Repeated below

2020-05-26 16:51 UTC, rajat2502 commented on index.html
> +    <meta name="keywords" content="Nibble Computer Society is the official computer society of JSS Noida. We are a group of students working towards enhancing knowledge in the field of computer scien
These are not keywords. Keywords can be Nibble Computer Society, NCS, JSS Noida, JSS, student society, computer society, etc

2020-05-26 16:51 UTC, rajat2502 commented on index.html
> +    <meta name="MobileOptimized" content="320"/>
remove this line.

2020-05-26 16:59 UTC, Shruti3004 commented
Okay sir

On Tue, 26 May 2020, 22:21 Rajat Verma, <notifications@github.com> wrote:

> *@rajat2502* requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/ncs-jss/ncs-jss.github.io/pull/37#discussion_r430560215>
> :
>
> > @@ -11,6 +11,34 @@
>      </script>
>      <meta charset="utf-8">
>      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
> +    <meta name="description" content="Nibble Computer Society">
>
> Repeated below
> ------------------------------
>
> In index.html
> <https://github.com/ncs-jss/ncs-jss.github.io/pull/37#discussion_r430560897>
> :
>
> > @@ -11,6 +11,34 @@
>      </script>
>      <meta charset="utf-8">
>      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
> +    <meta name="description" content="Nibble Computer Society">
> +    <meta name="keywords" content="Nibble Computer Society is the official computer society of JSS Noida. We are a group of students working towards enhancing knowledge in the field of computer science. The website shows our contribution to the college, our members and events & workshops that we organize."/>
>
> These are not keywords. Keywords can be Nibble Computer Society, NCS, JSS
> Noida, JSS, student society, computer society, etc
> ------------------------------
>
> In index.html
> <https://github.com/ncs-jss/ncs-jss.github.io/pull/37#discussion_r430562291>
> :
>
> > @@ -11,6 +11,34 @@
>      </script>
>      <meta charset="utf-8">
>      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
> +    <meta name="description" content="Nibble Computer Society">
> +    <meta name="keywords" content="Nibble Computer Society is the official computer society of JSS Noida. We are a group of students working towards enhancing knowledge in the field of computer science. The website shows our contribution to the college, our members and events & workshops that we organize."/>
> +    <meta name="HandheldFriendly" content="True"/>
> +    <meta name="MobileOptimized" content="320"/>
>
> remove this line.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ncs-jss/ncs-jss.github.io/pull/37#pullrequestreview-418489505>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMIRFZVOK4Z5HSTQAL7JXLRTPXSDANCNFSM4NKJK3QQ>
> .
>

2020-05-26 17:43 UTC, rajat2502 commented on index.html
> +    <meta name="description" content="Nibble Computer Society">
Better remove this one, as it does not contain the description.

2020-05-26 17:45 UTC, Shruti3004 commented
Okay sir
I will make the mentioned changes.

On Tue, 26 May 2020, 23:13 Rajat Verma, <notifications@github.com> wrote:

> *@rajat2502* commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/ncs-jss/ncs-jss.github.io/pull/37#discussion_r430592791>
> :
>
> > @@ -11,6 +11,34 @@
>      </script>
>      <meta charset="utf-8">
>      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
> +    <meta name="description" content="Nibble Computer Society">
>
> Better remove this one, as it does not contain the description.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ncs-jss/ncs-jss.github.io/pull/37#discussion_r430592791>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMIRF7MO6JAS4OTYXECDGDRTP5UNANCNFSM4NKJK3QQ>
> .
>

2020-05-28 13:32 UTC, rajat2502 commented
Any updates?

2020-05-28 15:05 UTC, Shruti3004 commented
@rajat2502 Sir I have made the changes please review it.

2020-05-29 05:24 UTC, rajat2502 commented
Add these meta tags to all the other pages as well. The content of the tags should be changed accordingly.

2020-05-29 17:08 UTC, rajat2502 commented on team/index.html
> +        <meta name="description" content="NCS is a student group that constantly tries to innovate and foster technical activities in the campus. Since 2000, we have focused on creating meaningful ex
@krrohitch @rex12543 Is this fine as the description of the team page?

2020-05-29 17:08 UTC, rajat2502 commented on project/index.html
> +    <meta name="description" content="We hope to bring the best in code, development and design to the college scene."/>
Also, this one.

2020-05-29 19:44 UTC, closed without merging