Creating CONTRIBUTING.md file
ncs-jss/ncs-jss.github.io pull request #6
Opened 2017-09-28 13:22 UTC by rsm23

Creating CONTRIBUTING.md file

2017-09-28 17:46 UTC, ankitjain28may requested changes

2017-09-28 17:46 UTC, ankitjain28may commented on CONTRIBUTING.md
> +0. [Fork the repo!](https://github.com/rsm23/ncs-jss.github.io/new/master#fork-destination-box)
Repo link should be the link of this repo rather than the link of your fork repo

2017-09-28 18:38 UTC, rsm23 commented
Yeah my bad. :grinning:

2017-10-26 10:09 UTC, ankitjain28may commented
@rsm23 Are you going to do this ?

2017-11-04 18:59 UTC, ankitjain28may requested changes

2017-11-04 18:59 UTC, ankitjain28may commented on CONTRIBUTING.md
> +0. Navigate to the project: `cd ncs-jss`.
It should be `cd ncs-jss.github.io`

2017-11-04 18:59 UTC, closed without merging